-- LEFT GET THE SPECIFIED NUMEBER OF LEFTMOST CHARACTER FROM STIRNG
select left("MYSQL LEFT",5);
select left("MYSQL LEFT",100);
select right("MYSQL LEFT",5);
-- REPLACE:- SEARCH AND REPLACE A SUBSTRING IN A STRING      
SELECT REPLACE ("SQL TUTORIAL","SQL","HTML") AS REPLACESTRING;
-- SUBSTRING:-- EXTRACT A SUBSTRING STARTING FROM A POSITION WITH A SPECIFIC LENGTH.
SELECT substring(string,start,length) ;-- syntax
select substring("Oracle",1,3);
